name: Lighthouse

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lighthouseci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "🔧 Set up Node"
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "⚡ Cache node modules"
        uses: actions/cache@v3
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: "📦 Install dependencies"
        #if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --prefer-offline --no-audit --progress=false && npm install -g @lhci/cli@0.8.x

      - name: "🏗 Build"
        working-directory: ${{ env.working-directory }}
        run: npm run build --if-present

      - name: "🧪 Run Lighthouse Test"
        run: lhci autorun