name: Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: yarn install, build
        run: |
          yarn install
          yarn run build
      - name: run Lighthouse CI
        run: |
          yarn global add @lhci/cli@0.8.x
          yarn add puppeteer
          lhci autorun --failOnUploadFailure=true 
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: lighthouse-report

    # Output the JSON to job summary 
    # head to https://googlechrome.github.io/lighthouse/viewer/