name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  client-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: ['16']
        os: [ubuntu-latest]

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - name: ♻️ Check out Git Repository
        uses: actions/checkout@v2

      - name: 🔖  Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: ⬇️  Install npm dependencies
        working-directory: ${{env.working-directory}}
        run: npm install

      - name: ✅  Run tests
        working-directory: ${{env.working-directory}}
        run: npm run test

      - name: 🔴 Lint all files
        working-directory: ${{env.working-directory}}
        run: npm run lint:check